[package]
name = "ennui-wgpu"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
log.workspace = true
bytemuck.workspace = true
ennui.workspace = true
ennui-pictures.workspace = true
ennui-platform.workspace = true
ennui-render.workspace = true
png.workspace = true
naga_oil.workspace = true
wgpu.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { workspace = true, features = ["fragile-send-sync-non-atomic-wasm"] }

[lints]
workspace = true
