use crate::data::{Asked, Request};
use editor_document::prelude::{Author, Book};
use ennui::reflect::prelude::Value;
use std::collections::VecDeque;
use std::net::TcpListener;
use std::path::PathBuf;

#[derive(Default)]
pub struct Editor {
    pub book: Book,
    pub happened: Vec<String>,
    pub(crate) said: Vec<String>,
    pub(crate) notices: Vec<String>,
    pub problems: Vec<String>,
    pub(crate) raised: Vec<crate::data::Problem>,
    pub(crate) withdrawn: Vec<crate::data::Problem>,
    pub(crate) standing: Vec<crate::data::Problem>,
    pub started: bool,
    pub(crate) author: Author,
    pub(crate) requests: VecDeque<Request>,
    pub(crate) answers: Vec<(u64, String)>,
    pub told: Vec<String>,
    pub(crate) quit: bool,
    pub picture: Option<(PathBuf, u64)>,
    pub(crate) pictured: Option<PathBuf>,
    pub disk_turn: u64,
    pub(crate) reloaded: Vec<String>,
    pub(crate) layout_text: String,
    pub(crate) layout_key: u64,
    pub(crate) layout_name: String,
    pub(crate) layouts: Vec<(String, String)>,
    pub(crate) layout_asked: Option<String>,
    pub(crate) pane_asked: Option<usize>,
    pub designing: Designing,
    pub showing: Option<(PathBuf, u64, String)>,
    pub summary: Option<(usize, u64, String)>,
}

#[derive(Default)]
pub(crate) struct Server {
    pub listener: Option<TcpListener>,
    pub asked: Vec<Asked>,
    pub next: u64,
}

pub struct Opening {
    pub root: PathBuf,
    pub scene: String,
    pub crash: Option<PathBuf>,
}

impl Default for Opening {
    fn default() -> Self {
        Self {
            root: PathBuf::from("."),
            scene: String::from("main"),
            crash: None,
        }
    }
}

#[derive(Default)]
pub struct Shell {
    pub(crate) laid: bool,
    pub(crate) scene: Option<ennui::prelude::Entity>,
    pub(crate) state: Option<ennui::prelude::Entity>,
    pub(crate) undo: Option<ennui::prelude::Entity>,
    pub(crate) redo: Option<ennui::prelude::Entity>,
    pub(crate) save: Option<ennui::prelude::Entity>,
    pub(crate) scenes: Option<ennui::prelude::Entity>,
    pub(crate) finder: Option<ennui::prelude::Entity>,
    pub(crate) filtered: String,
    pub(crate) undo_icon: Option<ennui::prelude::Entity>,
    pub(crate) redo_icon: Option<ennui::prelude::Entity>,
    pub(crate) undo_tip: Option<ennui::prelude::Entity>,
    pub(crate) redo_tip: Option<ennui::prelude::Entity>,
    pub(crate) help: Option<ennui::prelude::Entity>,
    pub(crate) problems: Option<ennui::prelude::Entity>,
    pub(crate) messages: Option<ennui::prelude::Entity>,
    pub(crate) problems_icon: Option<ennui::prelude::Entity>,
    pub(crate) problems_count: Option<ennui::prelude::Entity>,
    pub(crate) palette: Option<ennui::prelude::Entity>,
    pub(crate) searching: Option<ennui::prelude::Entity>,
    pub(crate) offered: crate::data::Watched<Vec<crate::data::Offered>>,
    pub(crate) revealing: Option<(String, f32)>,
    pub(crate) log_keys: [u64; 2],
    pub(crate) log_shelves: [Option<ennui::prelude::Entity>; 2],
    pub(crate) log_lines: [Option<ennui::prelude::Entity>; 2],
    pub(crate) log_copies: [Option<ennui::prelude::Entity>; 2],
    pub(crate) logged: Vec<crate::data::Logged>,
    pub(crate) unseen: usize,
    pub(crate) leave: Option<ennui::prelude::Entity>,
    pub(crate) leave_buttons: [Option<ennui::prelude::Entity>; 3],
    pub(crate) leaving: Option<String>,
    pub(crate) asker: Option<ennui::prelude::Entity>,
    pub(crate) asker_title: Option<ennui::prelude::Entity>,
    pub(crate) asker_field: Option<ennui::prelude::Entity>,
    pub(crate) asker_buttons: [Option<ennui::prelude::Entity>; 2],
    pub(crate) naming: Option<String>,
    pub(crate) confirm: Option<ennui::prelude::Entity>,
    pub(crate) confirm_title: Option<ennui::prelude::Entity>,
    pub(crate) confirm_text: Option<ennui::prelude::Entity>,
    pub confirm_buttons: [Option<ennui::prelude::Entity>; 2],
    pub(crate) confirming: Option<String>,
    pub(crate) scene_choices: Vec<crate::data::SceneChoice>,
    pub(crate) prefab_opener: Option<(ennui::prelude::Entity, String)>,
    pub(crate) story: Option<ennui::prelude::Entity>,
    pub(crate) story_rows: Option<ennui::prelude::Entity>,
    pub(crate) story_steps: Vec<(ennui::prelude::Entity, i64)>,
    pub(crate) story_shape: Option<(usize, usize, u64, u64)>,
    pub(crate) row_knobs: Vec<(crate::data::RowKnobs, String)>,
    pub(crate) hid: Vec<(String, ennui::prelude::Entity)>,
    pub(crate) scene_pane: Option<ennui::prelude::Entity>,
    pub text_pane: Option<[ennui::prelude::Entity; 3]>,
    pub timeline_pane: Option<[ennui::prelude::Entity; 3]>,
    pub(crate) board: Option<ennui::prelude::Entity>,
    pub(crate) panes: Vec<ennui::prelude::Entity>,
    pub(crate) layout: Option<String>,
    pub(crate) layout_label: Option<ennui::prelude::Entity>,
    pub(crate) layout_picks: Vec<crate::data::LayoutPick>,
    pub(crate) window: Option<ennui::prelude::Entity>,
    pub(crate) tab_pressed: Option<usize>,
    pub(crate) full_asked: bool,
    pub(crate) inspector_pane: Option<ennui::prelude::Entity>,
    pub(crate) hint: Option<ennui::prelude::Entity>,
    pub lists: Option<ennui::prelude::Entity>,
    pub top: Option<ennui::prelude::Entity>,
    pub screens_pane: Option<ennui::prelude::Entity>,
    pub(crate) outline: Option<ennui::prelude::Entity>,
    pub(crate) outline_rows: Vec<(ennui::prelude::Entity, String)>,
    pub(crate) outline_folds: Vec<(ennui::prelude::Entity, String)>,
    pub(crate) shut: std::collections::BTreeSet<String>,
    pub(crate) fold_all: Option<[ennui::prelude::Entity; 2]>,
    pub(crate) revealed: Vec<String>,
    pub(crate) dragging: Option<(String, [f32; 2], bool)>,
    pub(crate) outline_built: Option<Vec<crate::data::Outlined>>,
    pub(crate) outline_shape: Option<(u64, Vec<String>)>,
    pub(crate) outline_list: Option<ennui::prelude::Entity>,
    pub(crate) outline_empty: Option<ennui::prelude::Entity>,
    pub(crate) outline_shown: Vec<usize>,
    pub(crate) outline_key: u64,
    pub(crate) outline_made: u64,
    pub(crate) scroll_to: Option<String>,
    pub(crate) inspector: Option<ennui::prelude::Entity>,
    pub(crate) controls: Vec<crate::data::Control>,
    pub(crate) adder: Option<(ennui::prelude::Entity, Vec<String>)>,
    pub(crate) sections: Vec<crate::data::Section>,
    pub(crate) folded: Vec<String>,
    pub(crate) copied: Option<(String, Value)>,
    pub(crate) scrolled: Option<(ennui::prelude::Entity, Vec<String>)>,
    pub(crate) setting_adder: Option<(ennui::prelude::Entity, Vec<String>)>,
    pub(crate) opened_settings: Vec<String>,
    pub(crate) namer: Option<ennui::prelude::Entity>,
    pub(crate) prefabber: Option<ennui::prelude::Entity>,
    pub(crate) inspected: Option<(u64, Vec<String>, Vec<String>)>,
    pub(crate) refreshed: u64,
    pub(crate) said: String,
    pub(crate) told: Vec<(String, f32, bool, Option<&'static str>)>,
    pub(crate) pressed: Option<[f32; 2]>,
    pub(crate) hovered: Option<String>,
    pub(crate) pin_sheet: Option<ennui::prelude::Entity>,
    pub(crate) card: Option<ennui::prelude::Entity>,
    pub(crate) card_title: Option<ennui::prelude::Entity>,
    pub card_field: Option<ennui::prelude::Entity>,
    pub showing: bool,
    pub summary_card: Option<ennui::prelude::Entity>,
    pub summary_text: Option<ennui::prelude::Entity>,
    pub summary_buttons: [Option<ennui::prelude::Entity>; 2],
    pub summary_shown: Option<(usize, u64)>,
    pub pinning: Option<Option<String>>,
    pub(crate) arming: bool,
    pub(crate) context: Option<ennui::prelude::Entity>,
    pub(crate) context_items: Vec<crate::data::Command>,
    pub(crate) context_open: bool,
    pub(crate) row_pressed: Option<String>,
}

#[derive(Default)]
pub struct Designing {
    pub aspect: Option<[f32; 2]>,
    pub shown: Vec<String>,
    pub frame: Option<ennui::prelude::Entity>,
    pub hosted: Vec<ennui::prelude::Entity>,
    pub playing: Vec<String>,
    pub(crate) drag: Option<crate::data::UiDrag>,
    pub(crate) rims: [Option<ennui::prelude::Entity>; 2],
    pub(crate) handles: [Option<ennui::prelude::Entity>; 3],
}
